### PR TITLE
Update AWS broker catalog for RDS instances

### PR DESCRIPTION
**Pull request by ccostino**
**NOTE:** Please don't merge until @RonWilliams has a chance to see the new plans to make sure we're okay with those becoming available.

This changeset updates our AWS broker catalog to account for the following:

- We are not currently charging for any RDS instances (or any other service instances)
- We have added redundant versions of our new `micro-psql` and `small-mysql` plans
- We have added small and medium size burstable plan options (`db.t3.*`) for PostgreSQL (redundant and non-redundant)
- We have added medium size burstable plan options (`db.t2.*`) for MySQL (redundant and non-redundant)

TODO:
- [x] Update the names and descriptions with plain language to make it clearer what the differences are and to help guide customers to better choices

Our pricing will change again in FY21, but until that time there is no reason to display pricing information as we are not currently charging for the instances themselves ([only extra storage above 1TB](https://cloud.gov/pricing/#all-use-of-cloud-gov-includes)).  The existing pricing information is flowing through to the customer dashboard, which causes confusion about our billing.  Setting this to `0` should help alleviate that discrepancy.

Note that the new redundant plans (and all existing plans) are not set to free; free plans are available in sandboxes, and only the non-redundant `micro-psql` and `small-mysql` plans (as well as the shared versions for the time being) should be available for sandboxes.

## Changes proposed in this pull request:

- Update pricing of all service instances in our catalog to be `0` to reflect our current state
- Add redundant versions of our `micro-psql` and `small-mysql` plans
- Add new `small-psql` and `medium-psql` plans, including redundant versions
- Add new `medium-mysql` plan, including redundant version
- Rename existing plans and update all RDS plan descriptions to differentiate them better
- A bit of YAML formatting cleanup

## Security considerations

None: this is only expanding customer service offerings of existing public services and modifying our prices.

### CODE REVIEW

**Comment by RonWilliams** [comment]
Can we add t-series medium instance types for both postgres and mysql? We had a few services where m3.medium was too large, but small/micro was too small.

**Comment by ccostino** [comment]
@RonWilliams yes, we can add those.  I'll work them in and update the PR!

**Comment by ccostino** [comment]
I'm going to update the descriptions to be a bit more specific as a part of this, since we'll have both the memory optimized and burstable performance options for `medium` - I'll add in small too for Postgres so it's there.

**Comment by ccostino** [comment]
New plans are now in place, along with name and description updates!  However, these could benefit from some more plain language to make them easier to understand and guide customers toward better options for themselves.  I've marked this as a TODO and will keep this PR as a draft until that is done.

**Review by RonWilliams — APPROVED** [review]

**Comment by ccostino** [comment]
@RonWilliams, thanks for taking a look and approving!  There will be a few more cosmetic changes to plan names and descriptions, but I am taking your approval to mean that the new plans are clear to go once we're ready. :-)

**Pull request merged**
